# .â–„â–„ Â· â–„â–„â–„â–„â–„ â–„â–„â–„Â· â–„â–„â–„  .â–„â–„ Â·  â–„ .â–„â–ª   â–„â–„â–„Â·
# â–â–ˆ â–€. â€¢â–ˆâ–ˆ  â–â–ˆ â–€â–ˆ â–€â–„ â–ˆÂ·â–â–ˆ â–€. â–ˆâ–ˆâ–ªâ–â–ˆâ–ˆâ–ˆ â–â–ˆ â–„â–ˆ
# â–„â–€â–€â–€â–ˆâ–„ â–â–ˆ.â–ªâ–„â–ˆâ–€â–€â–ˆ â–â–€â–€â–„ â–„â–€â–€â–€â–ˆâ–„â–ˆâ–ˆâ–€â–â–ˆâ–â–ˆÂ· â–ˆâ–ˆâ–€Â·
# â–â–ˆâ–„â–ªâ–â–ˆ â–â–ˆâ–ŒÂ·â–â–ˆ â–ªâ–â–Œâ–â–ˆâ€¢â–ˆâ–Œâ–â–ˆâ–„â–ªâ–â–ˆâ–ˆâ–ˆâ–Œâ–â–€â–â–ˆâ–Œâ–â–ˆâ–ªÂ·â€¢
#  â–€â–€â–€â–€  â–€â–€â–€  â–€  â–€ .â–€  â–€ â–€â–€â–€â–€ â–€â–€â–€ Â·â–€â–€â–€.â–€   
# Created by: Jaden Wu
# Github: @jadnw
# Email: jadenwu137@protonmail.com

[username]
format = " [ï˜½ ]($style)"
style_user = "bold green"
style_root = "bold green"
show_always = true

[directory]
style = "cyan"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = ""

[git_status]
style = "white"
ahead = "ï˜¾ ${count}"
diverged = "ï„‚ ${ahead_count}; ï˜» ${behind_count}"
behind = "ï˜» ${count}"
deleted = "ïš¿"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = " î«² [$duration]($style)"
disabled = false

## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = " î‚  $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2
[character]
success_symbol = " [î‰](bold green)"
error_symbol = " [î®ˆ](bold red)"

[aws]
symbol = "ï”­ "

[conda]
symbol = "ğŸ"

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "ï³‘ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "ïŸ— "

[package]
symbol = "ï£• "

[perl]
symbol = "î© "

[php]
symbol = "ï³„ "

[python]
symbol = "îœ¼ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[swift]
symbol = "î• "
